services:
  postgres:
    image: postgres:17rc1-alpine3.20
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=expert
    ports:
      - 5436:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
